# Setup
title:        johnwmillr
tagline:      Everything you never knew you needed to know about John.
baseurl:      ""
paginate:     5

# About/contact
author:
  name:       John W. Miller
  url:        http://johnwmillr.com

# Gems
plugins_dir:
  
gems:
  - jemoji
  - jekyll-paginate

# Others
markdown: kramdown

# Default post values
permalink: "/:year/:title"

# https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"      